(load "procura.lisp")
(load "puzzle.lisp")

(defun t1 ()
  '(
    (02   20   44   nil  nil  nil  nil  nil  nil  nil)
    (nil  nil  nil  nil  nil  nil  nil  nil  nil  nil)
    (nil  03   30   nil  nil  nil  nil  nil  nil  nil)
    (nil  nil  nil  nil  nil  nil  nil  nil  nil  nil)
    (nil  nil  nil  22   nil  nil  nil  nil  nil  nil)
    (nil  nil  nil  nil  nil  nil  nil  nil  nil  nil)
    (nil  nil  nil  nil  nil  nil  nil  nil  nil  nil)
    (nil  nil  nil  nil  nil  nil  nil  nil  nil  nil)
    (nil  nil  nil  nil  nil  nil  nil  nil  nil  nil)
    (nil  nil  nil  nil  nil  nil  nil  nil  nil  nil)
  )
)

(defun t2 ()
  '(
    (98   97   96   95   94   93   92   91   90   89 )
    (01   02   03   04   05   55   06   07   08   09 )
    (nil  66   nil  nil  nil  nil  nil  nil  nil  11 )
    (nil  nil  nil  nil  nil  nil  nil  nil  nil  nil)
    (nil  nil  22   nil  nil  nil  nil  nil  33   nil)
    (nil  nil  nil  nil  nil  nil  nil  nil  nil  nil)
    (nil  nil  nil  88   nil  nil  nil  44   nil  nil)
    (nil  nil  nil  nil  nil  nil  nil  nil  nil  nil)
    (nil  nil  nil  nil  77   nil  nil  nil  nil  nil)
    (nil  nil  nil  nil  nil  nil  99   nil  nil  nil)
  ) 
)



'((((NIL 5 NIL NIL NIL 15 NIL NIL NIL NIL) 
    (NIL NIL NIL 6 NIL NIL NIL T NIL NIL)
   (NIL 4 NIL NIL NIL 14 NIL NIL NIL 24) 
    (NIL NIL NIL 7 NIL NIL NIL 17 NIL NIL)
   (NIL 3 NIL NIL NIL 13 NIL NIL NIL 23) 
    (NIL NIL NIL 8 NIL NIL NIL 18 NIL NIL)
   (NIL 2 NIL NIL NIL 12 NIL NIL NIL 22) 
    (NIL NIL NIL 9 NIL NIL NIL 19 NIL NIL)
   (NIL 1 NIL NIL NIL 11 NIL NIL NIL 21)
   (NIL NIL NIL 10 NIL NIL NIL 20 NIL NIL))
  (((NIL 5 NIL NIL NIL 15 NIL NIL NIL T) 
     (NIL NIL NIL 6 NIL NIL NIL 16 NIL NIL)
    (NIL 4 NIL NIL NIL 14 NIL NIL NIL 24)
    (NIL NIL NIL 7 NIL NIL NIL 17 NIL NIL)
    (NIL 3 NIL NIL NIL 13 NIL NIL NIL 23)
    (NIL NIL NIL 8 NIL NIL NIL 18 NIL NIL)
    (NIL 2 NIL NIL NIL 12 NIL NIL NIL 22)
    (NIL NIL NIL 9 NIL NIL NIL 19 NIL NIL)
    (NIL 1 NIL NIL NIL 11 NIL NIL NIL 21)
    (NIL NIL NIL 10 NIL NIL NIL 20 NIL NIL))
   NIL 300 25 0)
  300 41 1))